title: "Greg Wilson's Fiction"
author: "Greg Wilson"
repository: gvwilson/fiction
sidenotes: true
markdown: kramdown
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
exclude:
  - bin
  - README.md
  - '*~'
  - '*.txt'
